### PR TITLE
Added Vercel Deployment Capabilities

### PR DESCRIPTION
**Pull request by GhostOf0days**
This allows users to dynamically update their ReadMe without adding new commits as the Vercel website will be updated with new commits by the Github Actions bot.

### CODE REVIEW

**Comment by GhostOf0days** [comment]
Ready to merge. There was an issue with the ReadMe excluding something in a code block.

**Comment by GhostOf0days** [comment]
@agonyz

**Comment by GhostOf0days** [comment]
@agonyz

**Comment by agonyz** [comment]
@GhostOf0days I don't think you wanted to mention me, since I'm not the repo owner.

**Comment by GhostOf0days** [comment]
My bad. @yogeshwaran01

**Pull request closed without merging**
